name: CI/CD

on:
    push:
        branches:
        - main

env:
    BUILD_CONFIGURATION: Release

jobs:
    build_deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        env:
            BUILD_CONFIGURATION: Release
        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup .NET Core SDK
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9

            # Install EF Tool globally
            - name: Install EF Tool
              run: dotnet tool install --global dotnet-ef

            # Build the solution using supplied configuration
            - name: Build the solution
              run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

            # Build migrations script
            - name: Build migrations script
              run: >-
                dotnet ef migrations script
                --configuration ${{ env.BUILD_CONFIGURATION }}
                --idempotent
                --output ${{ github.workspace}}/migrations.sql
                --project Infrastructure
                --startup-project Api

            # Login to Azure
            - name: Login to Azure
              uses: azure/login@v2
              with:
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            # Deploy the migrations script to Azure SQL
            - name: Deploy migrations script to Azure SQL
              uses: azure/sql-action@2.3
              with:
                path: ${{ github.workspace }}/migrations.sql
                connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}